# Generated by Django 3.1.6 on 2021-02-26 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EngageApp', '0001_initial_manual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventconference_1',
            name='event_charges',
            field=models.FloatField(null=True),
        ),
    ]
