# Generated by Django 3.1.6 on 2021-02-25 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EngageApp', '0002_auto_20210225_1042'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupens',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('coupen_code', models.CharField(max_length=200)),
                ('discount_amount', models.FloatField()),
                ('status', models.CharField(max_length=100)),
                ('created_by_empid', models.IntegerField()),
                ('created_datetime', models.DateTimeField()),
                ('modified_datetime', models.DateTimeField()),
                ('event', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='EngageApp.eventdetails')),
            ],
        ),
    ]
