# Generated by Django 3.1.6 on 2021-02-27 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EngageApp', '0003_auto_20210226_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualregister',
            name='event_charges',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='virtualregister',
            name='tax',
            field=models.FloatField(null=True),
        ),
    ]
