# Generated by Django 3.1.6 on 2021-02-27 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EngageApp', '0004_auto_20210227_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdetails',
            name='update',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
