# Generated by Django 3.1.6 on 2021-02-25 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EngageApp', '0004_auto_20210225_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupens',
            name='event_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
