# Generated by Django 3.1.6 on 2021-03-01 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EngageApp', '0005_eventdetails_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupons',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
