# Generated by Django 3.1.7 on 2021-02-26 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EngageApp', '0005_coupens_event_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coupens',
            new_name='Coupons',
        ),
        migrations.RenameField(
            model_name='coupons',
            old_name='coupen_code',
            new_name='coupon_code',
        ),
    ]
