# Generated by Django 3.1.6 on 2021-03-09 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EngageApp', '0008_auto_20210305_1237'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('images', models.CharField(max_length=200)),
            ],
        ),
    ]
